routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Route::resource('job', 'JobController');
Route::resource('worker', 'WorkerController');
Route::resource('bedroom', 'BedroomController');

app/Job.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Job extends Model
{
    protected $fillable = [
        'title',
        'responsible',
        'phone',
        'address',
        'hourly_rate',
        'note' 
    ];
}

app/Http/Controllers/JobController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class JobController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // get all the nerds
        //$jobs = \App\job::all();
        $jobs = \App\job::orderBy('id', 'desc')->get();

        return view('job.index', compact('jobs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('job/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title'=> 'required',
            'responsible'=> 'required',
            'phone'=> 'required',
            'hourly_rate'=> 'required',
            'note'=> 'required',
            'address' => 'required',
        ]);
        $job = new \App\Job([
            'title' => $request->get('title'),
            'responsible' => $request->get('responsible'),
            'phone' => $request->get('phone'),
            'address' => $request->get('address'),
            'hourly_rate' => $request->get('hourly_rate'),
            'note' => $request->get('note'),
        ]);
        $job->save();
        return redirect('/job')->with('success', 'Oportunidade de trabalho salva com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/job/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dados da oportunidade de trabalho') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('job.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="title" class="col-md-4 col-form-label text-md-right">{{ __('Título do trabalho') }}</label>

                            <div class="col-md-6">
                                <input id="title" type="text" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" name="title" value="{{ old('title') }}" required>

                                @if ($errors->has('title'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="responsible" class="col-md-4 col-form-label text-md-right">{{ __('Qual o nome do responsável?') }}</label>

                            <div class="col-md-6">
                                <input id="responsible" type="text" class="form-control{{ $errors->has('responsible') ? ' is-invalid' : '' }}" name="responsible" value="{{ old('responsible') }}" required>

                                @if ($errors->has('responsible'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('responsible') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('Qual telefone do responsável?') }}</label>

                            <div class="col-md-6">
                                <input id="phone" type="text" class="form-control{{ $errors->has('phone') ? ' is-invalid' : '' }}" name="phone" value="{{ old('phone') }}" required>

                                @if ($errors->has('phone'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('phone') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="hourly_rate" class="col-md-4 col-form-label text-md-right">{{ __('Valor por hora?') }}</label>

                            <div class="col-md-6">
                                <input id="hourly_rate" type="text" class="form-control{{ $errors->has('hourly_rate') ? ' is-invalid' : '' }}" name="hourly_rate" value="{{ old('hourly_rate') }}">

                                @if ($errors->has('hourly_rate'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('hourly_rate') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="address" class="col-md-4 col-form-label text-md-right">{{ __('Qual o endereço do trabalho?') }}</label>

                            <div class="col-md-6">
                                <input id="address" type="text" class="form-control{{ $errors->has('address') ? ' is-invalid' : '' }}" name="address" value="{{ old('address') }}" required>

                                @if ($errors->has('address'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('address') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="note" class="col-md-4 col-form-label text-md-right">{{ __('Fale sobre o Trabalho') }}</label>

                            <div class="col-md-6">
                                <textarea id="note" type="text" style="height:120px" class="form-control{{ $errors->has('note') ? ' is-invalid' : '' }}" name="note" value="{{ old('note') }}" required>
                                </textarea>

                                @if ($errors->has('note'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('note') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Salvar') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/job/index.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>

<div class="uper">
    <div class="container-fluid mb-3 ">
        @if(session()->get('success'))
            <div class="alert alert-success">
            {{ session()->get('success') }}  
            </div><br />
        @endif
        <a class="btn btn-success mb-3" href="job/create" role="button">Cadastrar Trabalho</a>
        <a class="btn btn-info mb-3" href="worker/create" role="button">Quero me cadastrar</a>
    </div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Código</th>
                <th>Título</th>
                <th>Responsavel</th>
                <th>Valor</th>
                <th>Telefone</th>
                <th>Endereço</th>
                <th style="text-align:center">Observações</th>
            </tr>
        </thead>
        <tbody>
            @foreach($jobs as $job)
            <tr>
                <td>{{$job->id}}</td>
                <td>{{$job->title}}</td>
                <td>{{$job->responsible}}</td>
                <td>{{$job->value}}</td>
                <td>{{$job->phone}}</td>
                <td>{{$job->address}}</td>
                <td>{{$job->note}}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
<div>
@endsection