routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Route::resource('job', 'JobController');
Route::resource('worker', 'WorkerController');
Route::resource('bedroom', 'BedroomController');

app/Worker.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Worker extends Model
{
    protected $fillable = [
        'name', 
        'email', 
        'password', 
        'phone', 
        'your_job', 
        'address', 
        'speak_english', 
        'speak_spanish', 
        'have_car', 
        'have_drive_license', 
        'about'
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/WorkerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class WorkerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $workers = \App\Worker::orderBy('id', 'desc')->get();

        return view('worker.index', compact('workers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('worker/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:workers',
            'password' => 'required|string|min:6|confirmed',
            'phone' => 'required|string|max:255', 
            'your_job'=> 'required|string|max:255', 
            'address'=> 'required|string|max:255', 
            'speak_english'=> 'required|string|max:255', 
            'speak_spanish'=> 'required|string|max:255', 
            'have_car'=> 'required|string|max:255', 
            'have_drive_license'=> 'required|string|max:255', 
            'about'=> 'required|string|max:255',
        ]);
        $worker = new \App\Worker([
            'name' => $request->get('name'),
            'email' => $request->get('email'),
            'password' => Hash::make($request->get('password')),
            'phone' => $request->get('phone'), 
            'your_job' => $request->get('phone'), 
            'address'=> $request->get('address'), 
            'speak_english'=> $request->get('speak_english'), 
            'speak_spanish'=> $request->get('speak_spanish'), 
            'have_car'=> $request->get('have_car'), 
            'have_drive_license'=> $request->get('have_drive_license'), 
            'about'=> $request->get('about'),
        ]);
        $worker->save();
        return redirect('/worker')->with('success', 'Cadastro realizado com sucesso');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/worker/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dados para cadastro') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('worker.store') }}">
                        @csrf
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Seu nome') }}</label>
                            
                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('Seu telefone') }}</label>

                            <div class="col-md-6">
                                <input id="phone" type="text" class="form-control{{ $errors->has('phone') ? ' is-invalid' : '' }}" name="phone" value="{{ old('phone') }}" required>

                                @if ($errors->has('phone'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('phone') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>


                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('Seu e-Mail') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required>

                                @if ($errors->has('email'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="address" class="col-md-4 col-form-label text-md-right">{{ __('Qual cidade você mora?') }}</label>

                            <div class="col-md-6">
                                <input id="address" type="text" class="form-control{{ $errors->has('address') ? ' is-invalid' : '' }}" name="address" value="{{ old('address') }}" required>

                                @if ($errors->has('address'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('address') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="ingles" class="col-md-4 col-form-label text-md-right">{{ __('Você fala ingles?') }}</label>

                            <div class="col-md-6">
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="speak_english" id="Sim" value="Sim" checked>
                                    <label class="form-check-label" for="temcarro">
                                        Sim
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="speak_english" id="Não" value="Não">
                                    <label class="form-check-label" for="temcarro">
                                        Não
                                    </label>
                                </div>
                                @if ($errors->has('speak_english'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('speak_english') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="speak_spanish" class="col-md-4 col-form-label text-md-right">{{ __('Você fala espanhol?') }}</label>

                            <div class="col-md-6">
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="speak_spanish" id="Sim" value="Sim" checked>
                                    <label class="form-check-label" for="speak_spanish">
                                        Sim
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="speak_spanish" id="Não" value="Não">
                                    <label class="form-check-label" for="speak_spanish">
                                        Não
                                    </label>
                                </div>
                                @if ($errors->has('speak_spanish'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('speak_spanish') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="have_car" class="col-md-4 col-form-label text-md-right">{{ __('Você tem carro?') }}</label>

                            <div class="col-md-6">
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="have_car" id="Sim" value="Sim" checked>
                                    <label class="form-check-label" for="have_car">
                                        Sim
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="have_car" id="Não" value="Não">
                                    <label class="form-check-label" for="have_car">
                                        Não
                                    </label>
                                </div>
                                @if ($errors->has('have_car'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('have_car') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="have_drive_license" class="col-md-4 col-form-label text-md-right">{{ __('Você tem carteira?') }}</label>

                            <div class="col-md-6">
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="have_drive_license" id="have_drive_license" value="Sim" checked>
                                    <label class="form-check-label" for="exampleRadios1">
                                        Sim
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="have_drive_license" id="have_drive_license" value="Não">
                                    <label class="form-check-label" for="have_drive_license">
                                        Não
                                    </label>
                                </div>
                                @if ($errors->has('have_drive_license'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('have_drive_license') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="your_job" class="col-md-4 col-form-label text-md-right">{{ __('Qual a sua profissão?') }}</label>

                            <div class="col-md-6">
                                <input id="your_job" type="text" class="form-control{{ $errors->has('your_job') ? ' is-invalid' : '' }}" name="your_job" value="{{ old('your_job') }}" required>

                                @if ($errors->has('your_job'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('your_job') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="about" class="col-md-4 col-form-label text-md-right">{{ __('Fale sobre você') }}</label>

                            <div class="col-md-6">
                                <textarea id="about" type="text" style="height:120px" class="form-control{{ $errors->has('about') ? ' is-invalid' : '' }}" name="about" value="{{ old('about') }}" required>
                                </textarea>

                                @if ($errors->has('about'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('about') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <hr class="m-2">
                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Crie uma senha') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Repita sua senha') }}</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Salvar meus dados') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/worker/index.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>

<div class="uper">
    <div class="container-fluid mb-3 ">
        @if(session()->get('success'))
            <div class="alert alert-success">
            {{ session()->get('success') }}  
            </div><br />
        @endif
        <a class="btn btn-info mb-3" href="worker/create" role="button">Quero me cadastrar</a>
    </div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Código</th>
                <th>Nome</th>
                <th>Telefone</th>
                <th>E-mail</th>
                <th>Endereço</th>
                <th>Profissão</th>
                <th>Tem<br/>carro</th>
                <th>Fala<br/>Ingles</th>
                <th>Fala<br/>Espanhol</th>
                <th>Carteira<br/>de motorista</th>
                <th style="text-align:center">Observações</th>
            </tr>
        </thead>
        <tbody>
            @foreach($workers as $worker)
            <tr>
                <td>{{$worker->id}}</td>
                <td>{{$worker->name}}</td> 
                <td>{{$worker->phone}}</td> 
                <td>{{$worker->email}}</td> 
                <td>{{$worker->address}}</td> 
                <td>{{$worker->your_job}}</td> 
                <td>{{$worker->have_car}}</td> 
                <td>{{$worker->speak_english}}</td> 
                <td>{{$worker->speak_spanish}}</td>
                <td>{{$worker->have_drive_license}}</td> 
                <td>{{$worker->about}}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
<div>
@endsection